# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8b218870fd63717183ea98ed1b48afbaba889a79b43a41c46eea121f744a3330329db50d502c811ae0d92e628b594c76ee837efcb6ac584f9188d9878e5bd6

test:
  secret_key_base: dfe1b49e356d527088e2649654dd734b6b783da470c939f9f0219e23f54300a35a8a2da71d2c5c31b70154abc47dfc90000d20384671d212ceb8e881d809f8df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
